services:
  - type: web
    name: summarizer-server
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build:render
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: summarizer-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://summarizer-server-q12q.onrender.com/auth/google/callback
      - key: FRONTEND_URL
        value: https://summarizer-ui.vercel.app
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: summarizer-db
    databaseName: summarizer
    user: summarizer_user
    plan: free